### ISSUE TITLE
Support Spring Data Apache Geode

### ISSUE THREAD

**Issue by nebhale** [spring-cloud/spring-cloud-bindings#14]
Add [Spring Data Apache Geode](https://spring.io/projects/spring-data-geode) support.

**Comment by nebhale** [comment]
No work needs to be done.

**Comment by jxblum** [comment]
@nebhale + @ekcasey - I'd be curious to learn more about what led to "_No work needs to be done._"

Specifically, what has or has not be technically done or what (e.g. SDG, or SBDG) is handling this concern for SC bindings?

@ekcasey and I spoke awhile back but curious what our discussion and her further findings led to after we talked.

Thanks,
@jxblum

**Comment by ekcasey** [comment]
Hey @jxblum!

SBDG currently uses the flattened version of `VCAP_SERVICES` and `spring-cloud-bindings` registers a `kubernetesServiceBindingFlattened ` `PropertySource` that always provides the flattened bindings, `spring-cloud-bindings`. Therefore the level of support is analogous to what is currently required by SBDG without requiring additional work. The one caveat is that the service bindings generated by PCC include nested data that can't be represented in the new binding format.

Happy to chat more

**Comment by jxblum** [comment]
Hi @ekcasey - Thank you for your response.

Just a quick followup... Is this "`kubernetesServiceBindingFlattened`" `PropertySource` named as such?

Currently, inside SBDG, when I [construct](https://github.com/spring-projects/spring-boot-data-geode/blob/1.3.1.RELEASE/spring-geode-autoconfigure/src/main/java/org/springframework/geode/boot/autoconfigure/ClientSecurityAutoConfiguration.java#L232-L234) a helper object (i.e. `VcapPropertySource` instance) from the `Environment`, I am [expecting](https://github.com/spring-projects/spring-boot-data-geode/blob/1.3.1.RELEASE/spring-geode/src/main/java/org/springframework/geode/core/env/VcapPropertySource.java#L109) ([this](https://github.com/spring-projects/spring-boot-data-geode/blob/1.3.1.RELEASE/spring-geode/src/main/java/org/springframework/geode/core/env/VcapPropertySource.java#L75)) there to be a specifically named `PropertySource` called "vcap".

The "vcap" `PropertySource` is then further [validated](https://github.com/spring-projects/spring-boot-data-geode/blob/1.3.1.RELEASE/spring-geode/src/main/java/org/springframework/geode/core/env/VcapPropertySource.java#L128-L130) to contain specific properties (specifically, [using](https://github.com/spring-projects/spring-boot-data-geode/blob/1.3.1.RELEASE/spring-geode/src/main/java/org/springframework/geode/core/env/VcapPropertySource.java#L129) a pre-constructed/determined [`Predicate`](https://github.com/spring-projects/spring-boot-data-geode/blob/1.3.1.RELEASE/spring-geode/src/main/java/org/springframework/geode/core/env/VcapPropertySource.java#L96-L98)), which expects the "`vcap.application.name`" and "`vcap.application.uris`" property to exist.

I gather that we are essentially letting Spring Boot's existing [`CloudFoundryVcapPostProcessor`](https://docs.spring.io/spring-boot/docs/current/api/org/springframework/boot/cloud/CloudFoundryVcapEnvironmentPostProcessor.html) do its work then? Even inside a _Kubernetes_ environment?

**Comment by ekcasey** [comment]
> Just a quick followup... Is this "kubernetesServiceBindingFlattened" PropertySource named as such?

Yes!

> Currently, inside SBDG, when I construct a helper object (i.e. `VcapPropertySource` instance) from the Environment, I am expecting (this) there to be a specifically named PropertySource called "vcap".

To integrate with Spring Cloud Bindings, SBDG will likely need to look for the new `kubernetesServiceBindingFlattened` property source.

> I gather that we are essentially letting Spring Boot's existing `CloudFoundryVcapPostProcessor` do its work then? Even inside a Kubernetes environment?

This library works with credentials provided in the format specified in https://github.com/k8s-service-bindings/spec, or https://github.com/buildpacks/spec/blob/main/extensions/bindings.md (the latter will eventually be removed in favor of the former spec). In general, Spring Cloud Bindings are not CF-specific and therefore we make no assumptions about whether `CloudFoundryVcapPostProcessor` runs. TAS on k8s may or may not continue to set and use `VCAP_SERVICES` or `VCAP_APPLICATION`. I assume that, if service credentials are provided in `VCAP_SERVICES`, this would be a temporary solution for compatibility before migrating to the new specification, but I don't actually know what the plan is there.
