### ISSUE TITLE
Support Spring Data Pivotal GemFire

### ISSUE THREAD

**Issue by nebhale** [spring-cloud/spring-cloud-bindings#16]
Add [Spring Data Pivotal Gemfire](https://spring.io/projects/spring-data-gemfire) support.

**Comment by nebhale** [comment]
No work needs to be done.

**Comment by jxblum** [comment]
@nebhale + @ekcasey - See [here](https://github.com/spring-cloud/spring-cloud-bindings/issues/14#issuecomment-666869549).
