### ISSUE TITLE
Support Spring Data Envers

### ISSUE THREAD

**Issue by nebhale** [spring-cloud/spring-cloud-bindings#19]
Add [Spring Data Envers](https://spring.io/projects/spring-data-envers) support.

**Comment by ekcasey** [comment]
If I am understanding the Spring Data Envers docs correctly I don't believe we need to support this at the binding level. The connection/credential information is not necessary to configure Spring Data Envers. Users can already enable Envers in their applications using the existing bindings.

Feel free to reopen if you think I have this wrong.
