### ISSUE TITLE
Support Spring Cloud Gateway

### ISSUE THREAD

**Issue by nebhale** [spring-cloud/spring-cloud-bindings#28]
Add Spring Cloud Gateway support.

**Comment by ekcasey** [comment]
After some reading it doesn't seem like users will want to bind applications to Spring Cloud Gateway. Rather, they may want to bind a gateway application to a discovery service like Eureka or Consul. Our Eureka binding support and potential future support for Spring Cloud Consul (and maybe Spring Cloud Zookeeper?) may address common Spring Cloud Gateway use cases.
