### ISSUE TITLE
Whether CNB_BINDINGS will not be supported in the future

### ISSUE THREAD

**Issue by Real00** [spring-cloud/spring-cloud-bindings#54]
`TODO: Remove as CNB_BINDINGS ages out`
Does that mean no future support CNB_BINDINGS ？

Thank you for the consideration.

**Comment by ekcasey** [comment]
Hi @Real00, yes now that there is a generic spec for service bindings the CNB project would like to [deprecate and phase the Bindings extension spec](https://github.com/buildpacks/rfcs/blob/main/text/0055-deprecate-service-bindings.md). However, we won't deprecate support in spring-cloud-binding until the spec itself is formally deprecated and we won't remove the functionality without a long deprecation window.

I am going to close this but feel free to reopen if you have any additional questions.

cc @dmikusa-pivotal
