### ISSUE TITLE
Add sslmode and sslrootcert for cockroachDB/Postgresql

### ISSUE THREAD

**Issue by myeung18** [spring-cloud/spring-cloud-bindings#65]
CockroachDB Cloud, by default, uses one-way TLS for client and server authentication. To do so, the client application has to download the server CA Certificate (ie: root.crt), and the path of this file has to be set to sslrootcert and added to the connection string.
We need a way to let a client application be able to know the path of this root.crt and build up the connection URL

We should enhance PostgreSqlBindingsPropertiesProcessor to process the `sslmode`, `sslrootcert`, and `options` under  $SERVICE_BINDING_ROOT if they present, and construct the final connection URL with these properties.

e.g.:
bindings
└── crdb-app
   ├── database
   ├── host
   ├── **options**        
   ├── password
   ├── port
   ├── provider
   ├── **sslmode** 
   ├── **sslrootcert**
   ├── type
   ├── **root.cert**
   └── username

With this enhancement, spring-cloud-bindings can also work with [Service Binding Operator](https://github.com/redhat-developer/service-binding-operator) to provide seamless binding service for postgresql and cockroachdb applications.

PR: https://github.com/spring-cloud/spring-cloud-bindings/pull/66

**Comment by myeung18** [comment]
@dmikusa-pivotal @nebhale

**Comment by dmikusa-pivotal** [comment]
#65 has been merged, closing this out.
