### ISSUE TITLE
Publish to Maven Central

### ISSUE THREAD

**Issue by dmikusa** [spring-cloud/spring-cloud-bindings#71]
Right now, Spring Cloud Bindings is not published to Maven Central.

We should publish to Maven Central, so it's easier for users to add this to projects.

**Comment by spencergibb** [comment]
Considering that when (not if) repo.spring.io goes down there are production errors for users without a work around, I'd qualify this as a bug.

**Comment by goerge** [comment]
I just ran into the issue that https://repo.spring.io/release/org/springframework/cloud/spring-cloud-bindings/1.10.0/spring-cloud-bindings-1.10.0.ja is not available any more. I'm using paketo-buildpacks via spring boot's `bootBuildImage` task  Any workaround available?

**Comment by scottfrederick** [comment]
@goerge If you don't need Spring Cloud Bindings in your application, there is a workaround here: https://github.com/paketo-buildpacks/spring-boot/issues/225#issuecomment-1186597162

**Comment by dmikusa** [comment]
Cross-referencing. Please follow [this issue](https://github.com/paketo-buildpacks/spring-boot/issues/304). We'll post updates there.

**Comment by anthonydahanne** [comment]
The jar was published to Maven Central: https://central.sonatype.com/artifact/org.springframework.cloud/spring-cloud-bindings/1.11.0

This issue can be closed I guess?
