### ISSUE TITLE
Support for ssl.enabled

### ISSUE THREAD

**Issue by garreeoke** [spring-cloud/spring-cloud-bindings#76]
How can we enabled mapping ssl.enabled=true to enable connections to port 5671? Rabbitmq on AWS is only available on 5671 using ampqs.

**Comment by garreeoke** [comment]
Nevermind ... found how to use it by using the full ampqs in the addresses mapping.

**Comment by dmikusa-pivotal** [comment]
👍 That is what I would recommend for now. There has been some talk of this, but we have to have known properties on the service broker side as well. That is something we are still trying to sort out. For now, the URI should work.
