### ISSUE TITLE
Incorrect documentation for redis bindings 

### ISSUE THREAD

**Issue by gm2552** [spring-cloud/spring-cloud-bindings#79]
The documentation for cluster nodes for Redis lists the secret entry should is `{cluster-nodes}`.  This is incorrect as is should be '{cluster.nodes}`

https://github.com/spring-cloud/spring-cloud-bindings/blob/f807774639f84ead7617e64357ff4efad0e92ae6/src/main/java/org/springframework/cloud/bindings/boot/RedisBindingsPropertiesProcessor.java#L48

**Comment by dmikusa-pivotal** [comment]
Thanks
